import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";

export default [
    {
        input: "src/capture/dev.js",
        output: {
            file: "dist/capture.dev.js",
            format: "es",
            banner: "/* Capture Script (Dev) - Generated by Rollup */"
        },
        plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs()]
    },
    {
        input: "src/dev/index.js",
        output: {
            file: "dist/cloud139.dev.js",
            format: "es",
            banner: "/* Cloud139 Script (Dev) - Generated by Rollup */"
        },
        plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs()]
    }
];
