import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";

export default [
    {
        input: "src/capture/index.js",
        output: {
            file: "dist/capture.js",
            format: "es",
            banner: "/* Capture Script - Generated by Rollup */"
        },
        plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs(), terser()]
    },
    {
        input: "src/index.js",
        output: {
            file: "dist/cloud139.js",
            format: "es",
            banner: "/* Cloud139 Script - Generated by Rollup */"
        },
        plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs(), terser()]
    }
];
